# Generated by Django 5.2.11 on 2026-02-16 21:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('job_type', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('progress_message', models.CharField(blank=True, default='', max_length=200)),
                ('params', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(max_length=20)),
                ('strategy_name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('timerange', models.CharField(blank=True, default='', max_length=50)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('trades', models.JSONField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_results', to='analysis.backgroundjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('strategy_name', models.CharField(max_length=50)),
                ('top_results', models.JSONField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('total_combinations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_results', to='analysis.backgroundjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
