# Generated by Django 5.2.11 on 2026-03-10 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_backgroundjob_idx_job_status_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelPerformance',
            fields=[
                ('model_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('total_predictions', models.IntegerField(default=0)),
                ('correct_predictions', models.IntegerField(default=0)),
                ('rolling_accuracy', models.FloatField(default=0.0, help_text='Rolling accuracy 0.0-1.0')),
                ('accuracy_by_regime', models.JSONField(blank=True, default=dict)),
                ('retrain_recommended', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('prediction_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('model_id', models.CharField(db_index=True, max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('asset_class', models.CharField(choices=[('crypto', 'Crypto'), ('equity', 'Equity'), ('forex', 'Forex')], default='crypto', max_length=10)),
                ('probability', models.FloatField(help_text='Calibrated probability 0.0-1.0')),
                ('confidence', models.FloatField(default=0.0)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=4)),
                ('regime', models.CharField(blank=True, default='', max_length=30)),
                ('actual_direction', models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down')], max_length=4, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-predicted_at'],
                'indexes': [models.Index(fields=['model_id', '-predicted_at'], name='idx_mlpred_model_date'), models.Index(fields=['symbol', '-predicted_at'], name='idx_mlpred_symbol_date')],
            },
        ),
    ]
