# Generated by Django 5.2.11 on 2026-03-10 21:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_add_mlprediction_mlmodelperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalAttribution',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=36)),
                ('symbol', models.CharField(max_length=20)),
                ('asset_class', models.CharField(choices=[('crypto', 'Crypto'), ('equity', 'Equity'), ('forex', 'Forex')], default='crypto', max_length=10)),
                ('strategy', models.CharField(max_length=100)),
                ('composite_score', models.FloatField()),
                ('ml_contribution', models.FloatField(default=0.0)),
                ('sentiment_contribution', models.FloatField(default=0.0)),
                ('regime_contribution', models.FloatField(default=0.0)),
                ('scanner_contribution', models.FloatField(default=0.0)),
                ('screen_contribution', models.FloatField(default=0.0)),
                ('win_rate_contribution', models.FloatField(default=0.0)),
                ('position_modifier', models.FloatField(default=1.0)),
                ('entry_regime', models.CharField(blank=True, default='', max_length=30)),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('open', 'Open')], default='open', max_length=4)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['symbol', '-recorded_at'], name='idx_sigattr_symbol_date'), models.Index(fields=['strategy', 'asset_class', '-recorded_at'], name='idx_sigattr_strat_asset'), models.Index(fields=['outcome', '-recorded_at'], name='idx_sigattr_outcome_date')],
            },
        ),
    ]
