# Generated by Django 5.2.11 on 2026-03-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_add_signal_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalattribution',
            name='technical_contribution',
            field=models.FloatField(default=0.0),
        ),
    ]
