# Generated by Django 5.2.11 on 2026-02-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_holding_asset_class_portfolio_asset_class'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('portfolio', 'symbol'), name='uniq_holding_portfolio_symbol'),
        ),
    ]
