# Generated by Django 5.2.11 on 2026-02-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_holding_uniq_holding_portfolio_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='exchange_id',
            field=models.CharField(default='kraken', max_length=50),
        ),
    ]
