# Generated by Django 5.2.11 on 2026-02-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.IntegerField(db_index=True)),
                ('event_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('channel', models.CharField(default='log', max_length=20)),
                ('delivered', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.IntegerField(db_index=True, unique=True)),
                ('max_portfolio_drawdown', models.FloatField(default=0.15)),
                ('max_single_trade_risk', models.FloatField(default=0.03)),
                ('max_daily_loss', models.FloatField(default=0.05)),
                ('max_open_positions', models.IntegerField(default=10)),
                ('max_position_size_pct', models.FloatField(default=0.2)),
                ('max_correlation', models.FloatField(default=0.7)),
                ('min_risk_reward', models.FloatField(default=1.5)),
                ('max_leverage', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='RiskMetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.IntegerField(db_index=True)),
                ('var_95', models.FloatField(default=0.0)),
                ('var_99', models.FloatField(default=0.0)),
                ('cvar_95', models.FloatField(default=0.0)),
                ('cvar_99', models.FloatField(default=0.0)),
                ('method', models.CharField(default='parametric', max_length=20)),
                ('drawdown', models.FloatField(default=0.0)),
                ('equity', models.FloatField(default=0.0)),
                ('open_positions_count', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.IntegerField(db_index=True, unique=True)),
                ('total_equity', models.FloatField(default=10000.0)),
                ('peak_equity', models.FloatField(default=10000.0)),
                ('daily_start_equity', models.FloatField(default=10000.0)),
                ('daily_pnl', models.FloatField(default=0.0)),
                ('total_pnl', models.FloatField(default=0.0)),
                ('open_positions', models.JSONField(blank=True, default=dict)),
                ('is_halted', models.BooleanField(default=False)),
                ('halt_reason', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.IntegerField(db_index=True)),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=10)),
                ('size', models.FloatField()),
                ('entry_price', models.FloatField()),
                ('stop_loss_price', models.FloatField(blank=True, null=True)),
                ('approved', models.BooleanField()),
                ('reason', models.CharField(max_length=500)),
                ('equity_at_check', models.FloatField(default=0.0)),
                ('drawdown_at_check', models.FloatField(default=0.0)),
                ('open_positions_at_check', models.IntegerField(default=0)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
