# Generated by Django 5.2.11 on 2026-03-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_risklimitchange_alertlog_idx_alert_portfolio_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradechecklog',
            name='composite_score',
            field=models.FloatField(blank=True, help_text='Conviction composite score (0-100) from SignalAggregator', null=True),
        ),
    ]
