# Generated by Django 5.2.11 on 2026-03-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_add_composite_score_to_tradechecklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskstate',
            name='crypto_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='riskstate',
            name='declared_capital',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='riskstate',
            name='equity_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='riskstate',
            name='forex_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='riskstate',
            name='daily_start_equity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='riskstate',
            name='peak_equity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='riskstate',
            name='total_equity',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='CapitalLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.IntegerField(db_index=True)),
                ('entry_type', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('balance_after', models.FloatField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['portfolio_id', '-created_at'], name='idx_ledger_port_time')],
            },
        ),
    ]
