# Generated by Django 5.2.11 on 2026-02-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('exchange_id', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('volume_24h', models.FloatField(default=0.0)),
                ('change_24h', models.FloatField(default=0.0)),
                ('high_24h', models.FloatField(default=0.0)),
                ('low_24h', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
