# Generated by Django 5.2.11 on 2026-02-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_datasourceconfig_asset_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('source', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('symbols', models.JSONField(blank=True, default=list)),
                ('asset_class', models.CharField(choices=[('crypto', 'Crypto'), ('equity', 'Equity'), ('forex', 'Forex')], db_index=True, default='crypto', max_length=10)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('sentiment_label', models.CharField(default='neutral', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['asset_class', '-published_at'], name='market_news_asset_c_35a733_idx')],
            },
        ),
    ]
