# Generated by Django 5.2.11 on 2026-02-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_news_article'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='marketdata',
            constraint=models.UniqueConstraint(fields=('symbol', 'exchange_id', 'timestamp'), name='uniq_marketdata_symbol_exchange_ts'),
        ),
    ]
