# Generated by Django 5.2.11 on 2026-02-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.CharField(max_length=50)),
                ('exchange_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=10)),
                ('order_type', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('price', models.FloatField(default=0.0)),
                ('filled', models.FloatField(default=0.0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
