# Generated by Django 5.2.11 on 2026-03-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scheduled_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='cron_schedule',
            field=models.CharField(blank=True, default='', help_text="Cron expression (5-field) with optional timezone, e.g. '0 17 * * *|US/Eastern'. Takes precedence over interval_seconds.", max_length=100),
        ),
    ]
